### ISSUE TITLE
Failures on invalid ranges

### ISSUE THREAD

**Issue by jb55** [adnelson/semver-range#3]
npm seems to safely ignore the end of this semver:

https://github.com/EvanOxfeld/node-pullstream/blob/53345fae0653f41ff60bc56b18fa4a6775716cf0/package.json#L23

Should we?

Right now nixfromnpm fails on this repo.

**Comment by jb55** [comment]
Actually I'm not even sure it would be easy or wise to support cases like this, should just get it fixed upstream

**Comment by adnelson** [comment]
I've been dealing with a few weird edge cases myself, and I'm not sure what the best way to approach it is. I suppose in this case it's pretty simple (we just change the parser not to require `eof` as a final parse) but I'm not sure what kind of complications that's going to have.

One of the annoying things I'm seeing right now is that situations like this are ambiguous: `1.2.3-2` could be a single version, where `2` is a release tag, or a version range from `1.2.3` to `2.0.0`. As it is, I'm requiring whitespace between the hyphens, but I've seen a few packages where `npm` treats it differently. I think they just use regexes; it might be best just to copy their regex rules rather than using parsec....

**Comment by jb55** [comment]
yeah I'm running into that issue now (I think?): 

```
readable-stream is broken: NoMatchingVersion >=1.0.33-1 <1.1.0-0
```

**Comment by adnelson** [comment]
This is fixed now
